# Generated by Django 2.2.10 on 2021-09-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_answertype_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnswerType',
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('Text', 'текстом'), ('Single', 'выбор одного варианта'), ('Multi', 'выбор нескольких вариантов')], default=('Text', 'текстом'), max_length=6, verbose_name='Тип ответа'),
        ),
    ]
