# Generated by Django 2.2.10 on 2021-09-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210921_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='poll',
            new_name='poll_id',
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('Text', 'текстом'), ('Single', 'выбор одного варианта'), ('Multi', 'выбор нескольких вариантов')], default='Text', max_length=6, verbose_name='Тип ответа'),
        ),
    ]
